import { c } from "../helpers.mjs";

/** Albania municipalities */
export default [
  c("Berat", "Berat"),
  c("Bulqizë", "Bulqizë"),
  c("Delvinë", "Delvinë"),
  c("Devoll", "Devoll"),
  c("Dibër", "Dibër"),
  c("Dimal", "Dimal"),
  c("Dropull", "Dropull"),
  c("Durrës", "Durrës"),
  c("Elbasan", "Elbasan"),
  c("Fier", "Fier"),
  c("Finiq", "Finiq"),
  c("Gjirokastër", "Gjirokastër"),
  c("Gramsh", "Gramsh"),
  c("Has", "Has"),
  c("Himara", "Himarë"),
  c("Kamëz", "Kamëz"),
  c("Kavajë", "Kavajë"),
  c("Këlcyrë", "Këlcyrë"),
  c("Klosi", "Klosi"),
  c("Kolonjë", "Kolonjë"),
  c("Konispol", "Konispol"),
  c("Korçë", "Korçë"),
  c("Krastë", "Krastë"),
  c("Krujë", "Krujë"),
  c("Kuçovë", "Kuçovë"),
  c("Kukës", "Kukës"),
  c("Kurbin", "Kurbin"),
  c("Lezhë", "Lezhë"),
  c("Libohovë", "Libohovë"),
  c("Librazhd", "Librazhd"),
  c("Lushnjë", "Lushnjë"),
  c("Malësi e Madhe", "Malësi e Madhe"),
  c("Mallakastër", "Mallakastër"),
  c("Mat", "Mat"),
  c("Memaliaj", "Memaliaj"),
  c("Mirditë", "Mirditë"),
  c("Patos", "Patos"),
  c("Peqin", "Peqin"),
  c("Përmet", "Përmet"),
  c("Pogradec", "Pogradec"),
  c("Poliçan", "Poliçan"),
  c("Prrenjas", "Prrenjas"),
  c("Pukë", "Pukë"),
  c("Roskovec", "Roskovec"),
  c("Rrogozhinë", "Rrogozhinë"),
  c("Sarandë", "Sarandë"),
  c("Selenicë", "Selenicë"),
  c("Shkodër", "Shkodër"),
  c("Skrapar", "Skrapar"),
  c("Tepelenë", "Tepelenë"),
  c("Tirana", "Tirana"),
  c("Tropojë", "Tropojë"),
  c("Ura Vajgurore", "Ura Vajgurore"),
  c("Vau i Dejës", "Vau i Dejës"),
  c("Vlorë", "Vlorë"),
  c("Vorë", "Vorë"),
];
