import { same } from "../helpers.mjs";

/** All municipalities in Bosnia and Herzegovina */
export default same(
  "Banovići",
  "Banja Luka",
  "Bihać",
  "Bijeljina",
  "Bileća",
  "Bosanska Dubica",
  "Bosanska Gradiška",
  "Bosanska Krupa",
  "Bosanska Kostajnica",
  "Bosanski Brod",
  "Bosanski Novi",
  "Bosanski Petrovac",
  "Bosanski Šamac",
  "Brčko",
  "Breza",
  "Bugojno",
  "Busovača",
  "Cazin",
  "Centar Sarajevo",
  "Čapljina",
  "Čajniče",
  "Čelinac",
  "Čitluk",
  "Derventa",
  "Doboj",
  "Doboj East",
  "Doboj South",
  "Domaljevac-Šamac",
  "Donji Vakuf",
  "Drvar",
  "Foča",
  "Fojnica",
  "Gacko",
  "Glamoč",
  "Goražde",
  "Gračanica",
  "Gradačac",
  "Gradiška",
  "Grude",
  "Hadžići",
  "Han Pijesak",
  "Ilidža",
  "Ilijaš",
  "Jablanica",
  "Jajce",
  "Kakanj",
  "Kalesija",
  "Kalinovik",
  "Kiseljak",
  "Kladanj",
  "Ključ",
  "Konjic",
  "Kostajnica",
  "Kreševo",
  "Krupa na Uni",
  "Kupres",
  "Laktaši",
  "Livno",
  "Lopare",
  "Lukavac",
  "Ljubinje",
  "Ljubuški",
  "Maglaj",
  "Modriča",
  "Mostar",
  "Mrkonjić Grad",
  "Neum",
  "Nevesinje",
  "Novi Grad Sarajevo",
  "Novi Grad",
  "Novi Travnik",
  "Novo Sarajevo",
  "Odžak",
  "Olovo",
  "Orašje",
  "Pale",
  "Pelagićevo",
  "Petrovac",
  "Petrovo",
  "Posušje",
  "Prijedor",
  "Prnjavor",
  "Prozor-Rama",
  "Ravno",
  "Rogatica",
  "Rudo",
  "Sanski Most",
  "Sapna",
  "Šekovići",
  "Šipovo",
  "Široki Brijeg",
  "Srebrenica",
  "Srebrenik",
  "Stari Grad Sarajevo",
  "Stolac",
  "Tešanj",
  "Teočak",
  "Tomislavgrad",
  "Travnik",
  "Trebinje",
  "Trnovo",
  "Tuzla",
  "Ugljevik",
  "Usora",
  "Vareš",
  "Visoko",
  "Višegrad",
  "Vitez",
  "Vlasenica",
  "Vogošća",
  "Zavidovići",
  "Zenica",
  "Žepče",
  "Živinice",
  "Zvornik",
);
