import { c, same } from "../helpers.mjs";

/** North Macedonia municipalities */
export default [
  c("Aračinovo", "Aračinovo"),
  c("Berovo", "Berovo"),
  c("Bitola", "Bitola"),
  c("Bogdanci", "Bogdanci"),
  c("Bogovinje", "Bogovinje"),
  c("Bosilovo", "Bosilovo"),
  c("Brvenica", "Brvenica"),
  c("Butel", "Butel"),
  c("Čair", "Čair"),
  c("Čaška", "Čaška"),
  c("Centar", "Centar"),
  c("Centar Župa", "Centar Župa"),
  c("Češinovo-Obleševo", "Češinovo-Obleševo"),
  c("Čučer-Sandevo", "Čučer-Sandevo"),
  c("Debar", "Debar"),
  c("Debarca", "Debarca"),
  c("Delčevo", "Delčevo"),
  c("Demir Hisar", "Demir Hisar"),
  c("Demir Kapija", "Demir Kapija"),
  c("Dojran", "Dojran"),
  c("Dolneni", "Dolneni"),
  c("Drugovo", "Drugovo"),
  c("Gazi Baba", "Gazi Baba"),
  c("Gevgelija", "Gevgelija"),
  c("Gjorče Petrov", "Gjorče Petrov"),
  c("Gostivar", "Gostivar"),
  c("Gradsko", "Gradsko"),
  c("Greater Skopje", "Skopje"),
  c("Ilinden", "Ilinden"),
  c("Jegunovce", "Jegunovce"),
  c("Karbinci", "Karbinci"),
  c("Karpoš", "Karpoš"),
  c("Kavadarci", "Kavadarci"),
  c("Kičevo", "Kičevo"),
  c("Kisela Voda", "Kisela Voda"),
  c("Kočani", "Kočani"),
  c("Konče", "Konče"),
  c("Kratovo", "Kratovo"),
  c("Kriva Palanka", "Kriva Palanka"),
  c("Krivogaštani", "Krivogaštani"),
  c("Kruševo", "Kruševo"),
  c("Kumanovo", "Kumanovo"),
  c("Lipkovo", "Lipkovo"),
  c("Lozovo", "Lozovo"),
  c("Makedonska Kamenica", "Makedonska Kamenica"),
  c("Makedonski Brod", "Makedonski Brod"),
  c("Mavrovo and Rostuša", "Mavrovo i Rostuše"),
  c("Mogila", "Mogila"),
  c("Negotino", "Negotino"),
  c("Novaci", "Novaci"),
  c("Novo Selo", "Novo Selo"),
  c("Ohrid", "Ohrid"),
  c("Oslomej", "Oslomej"),
  c("Pehčevo", "Pehčevo"),
  c("Petrovec", "Petrovec"),
  c("Plasnica", "Plasnica"),
  c("Prilep", "Prilep"),
  c("Probištip", "Probištip"),
  c("Radoviš", "Radoviš"),
  c("Rankovce", "Rankovce"),
  c("Resen", "Resen"),
  c("Rosoman", "Rosoman"),
  c("Saraj", "Saraj"),
  c("Sopište", "Sopište"),
  c("Staro Nagoričane", "Staro Nagoričane"),
  c("Štip", "Štip"),
  c("Struga", "Struga"),
  c("Strumica", "Strumica"),
  c("Studeničani", "Studeničani"),
  c("Šuto Orizari", "Šuto Orizari"),
  c("Sveti Nikole", "Sveti Nikole"),
  c("Tearce", "Tearce"),
  c("Tetovo", "Tetovo"),
  c("Valandovo", "Valandovo"),
  c("Vasilevo", "Vasilevo"),
  c("Veles", "Veles"),
  c("Vevčani", "Vevčani"),
  c("Vinica", "Vinica"),
  c("Vraneštica", "Vraneštica"),
  c("Vrapčište", "Vrapčište"),
  c("Zajas", "Zajas"),
  c("Zelenikovo", "Zelenikovo"),
  c("Želino", "Želino"),
  c("Zrnovci", "Zrnovci"),
];
