import { c } from "../helpers.mjs";

/** All Serbian municipalities / city seats */
export default [
  c("Ada", "Ada"),
  c("Aleksandrovac", "Aleksandrovac"),
  c("Aleksinac", "Aleksinac"),
  c("Alibunar", "Alibunar"),
  c("Apatin", "Apatin"),
  c("Aranđelovac", "Aranđelovac"),
  c("Arilje", "Arilje"),
  c("Babušnica", "Babušnica"),
  c("Bač", "Bač"),
  c("Bačka Palanka", "Bačka Palanka"),
  c("Bačka Topola", "Bačka Topola"),
  c("Bački Petrovac", "Bački Petrovac"),
  c("Bajina Bašta", "Bajina Bašta"),
  c("Barajevo", "Barajevo"),
  c("Batočina", "Batočina"),
  c("Bečej", "Bečej"),
  c("Bela Palanka", "Bela Palanka"),
  c("Belgrade", "Beograd"),
  c("Beočin", "Beočin"),
  c("Blace", "Blace"),
  c("Bogatić", "Bogatić"),
  c("Bojnik", "Bojnik"),
  c("Boljevac", "Boljevac"),
  c("Bor", "Bor"),
  c("Bosilegrad", "Bosilegrad"),
  c("Brus", "Brus"),
  c("Bujanovac", "Bujanovac"),
  c("Crna Trava", "Crna Trava"),
  c("Čačak", "Čačak"),
  c("Čajetina", "Čajetina"),
  c("Ćićevac", "Ćićevac"),
  c("Čoka", "Čoka"),
  c("Ćuprija", "Ćuprija"),
  c("Despotovac", "Despotovac"),
  c("Dimitrovgrad", "Dimitrovgrad"),
  c("Doljevac", "Doljevac"),
  c("Gadžin Han", "Gadžin Han"),
  c("Golubac", "Golubac"),
  c("Gornji Milanovac", "Gornji Milanovac"),
  c("Inđija", "Inđija"),
  c("Irig", "Irig"),
  c("Ivanjica", "Ivanjica"),
  c("Jagodina", "Jagodina"),
  c("Kikinda", "Kikinda"),
  c("Kladovo", "Kladovo"),
  c("Knić", "Knić"),
  c("Knjaževac", "Knjaževac"),
  c("Koceljeva", "Koceljeva"),
  c("Kosjerić", "Kosjerić"),
  c("Kostolac", "Kostolac"),
  c("Kovačica", "Kovačica"),
  c("Kovin", "Kovin"),
  c("Kragujevac", "Kragujevac"),
  c("Kraljevo", "Kraljevo"),
  c("Krupanj", "Krupanj"),
  c("Kruševac", "Kruševac"),
  c("Kula", "Kula"),
  c("Kuršumlija", "Kuršumlija"),
  c("Lajkovac", "Lajkovac"),
  c("Lapovo", "Lapovo"),
  c("Lebane", "Lebane"),
  c("Leskovac", "Leskovac"),
  c("Loznica", "Loznica"),
  c("Lučani", "Lučani"),
  c("Ljig", "Ljig"),
  c("Ljubovija", "Ljubovija"),
  c("Majdanpek", "Majdanpek"),
  c("Mali Iđoš", "Mali Iđoš"),
  c("Mali Zvornik", "Mali Zvornik"),
  c("Malo Crniće", "Malo Crniće"),
  c("Medveđa", "Medveđa"),
  c("Merošina", "Merošina"),
  c("Mionica", "Mionica"),
  c("Negotin", "Negotin"),
  c("Niš", "Niš"),
  c("Nova Crnja", "Nova Crnja"),
  c("Nova Varoš", "Nova Varoš"),
  c("Novi Bečej", "Novi Bečej"),
  c("Novi Kneževac", "Novi Kneževac"),
  c("Novi Pazar", "Novi Pazar"),
  c("Novi Sad", "Novi Sad"),
  c("Odžaci", "Odžaci"),
  c("Opovo", "Opovo"),
  c("Osečina", "Osečina"),
  c("Pančevo", "Pančevo"),
  c("Paraćin", "Paraćin"),
  c("Pećinci", "Pećinci"),
  c("Petrovac na Mlavi", "Petrovac na Mlavi"),
  c("Pirot", "Pirot"),
  c("Plandište", "Plandište"),
  c("Požarevac", "Požarevac"),
  c("Požega", "Požega"),
  c("Preševo", "Preševo"),
  c("Priboj", "Priboj"),
  c("Prijepolje", "Prijepolje"),
  c("Prokuplje", "Prokuplje"),
  c("Rača", "Rača"),
  c("Raška", "Raška"),
  c("Rekovac", "Rekovac"),
  c("Ruma", "Ruma"),
  c("Sečanj", "Sečanj"),
  c("Senta", "Senta"),
  c("Šabac", "Šabac"),
  c("Šid", "Šid"),
  c("Sjenica", "Sjenica"),
  c("Smederevo", "Smederevo"),
  c("Smederevska Palanka", "Smederevska Palanka"),
  c("Sokobanja", "Sokobanja"),
  c("Sombor", "Sombor"),
  c("Sremska Mitrovica", "Sremska Mitrovica"),
  c("Sremski Karlovci", "Sremski Karlovci"),
  c("Stara Pazova", "Stara Pazova"),
  c("Subotica", "Subotica"),
  c("Surdulica", "Surdulica"),
  c("Svilajnac", "Svilajnac"),
  c("Svrljig", "Svrljig"),
  c("Temerin", "Temerin"),
  c("Titel", "Titel"),
  c("Topola", "Topola"),
  c("Trgovište", "Trgovište"),
  c("Trstenik", "Trstenik"),
  c("Tutin", "Tutin"),
  c("Ub", "Ub"),
  c("Užice", "Užice"),
  c("Valjevo", "Valjevo"),
  c("Varvarin", "Varvarin"),
  c("Velika Plana", "Velika Plana"),
  c("Veliko Gradište", "Veliko Gradište"),
  c("Vladimirci", "Vladimirci"),
  c("Vlasotince", "Vlasotince"),
  c("Vladičin Han", "Vladičin Han"),
  c("Vranje", "Vranje"),
  c("Vrbas", "Vrbas"),
  c("Vrnjačka Banja", "Vrnjačka Banja"),
  c("Vršac", "Vršac"),
  c("Zaječar", "Zaječar"),
  c("Zrenjanin", "Zrenjanin"),
  c("Žabalj", "Žabalj"),
  c("Žabari", "Žabari"),
  c("Žagubica", "Žagubica"),
  c("Žitište", "Žitište"),
  c("Žitorađa", "Žitorađa"),
];
